apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: bsathi2020-dev
data:
  my.cnf: |
    [mysqld]
    innodb_redo_log_capacity = 2G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: bsathi2020-dev
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  template:
    metadata:
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      initContainers:
      - name: fix-mysql-datadir
        image: busybox
        command: ["sh", "-c", "COUNT=$(ls -A /var/lib/mysql | grep -v lost+found | wc -l); if [ \"$COUNT\" -eq 0 ]; then rm -rf /var/lib/mysql/lost+found; fi"]
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      containers:
      - name: mysql
        image: bsathi2020/mysql:v1
        imagePullPolicy: Always
        startupProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/my.cnf
          subPath: my.cnf
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-config
          configMap:
            name: mysql
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: bsathi2020-dev
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
